Lang = {
    --Client
    rent = "Rent",
    rent_description = "Rent deposit",
    sell = "Sell",
    sell_description = "Sell your deposit",
    open = "Open",
    open_description = "Open deposit",
    change_lock = "Change lock",
    change_lock_description = "Change lock on deposit",
    duplicate_key = "Duplicate key",
    duplicate_key_description = "Duplicate key deposit",
    close = "Close",
    close_description = "Close menu",
    new_name = "Enter new key name",
    insert_deposit = "Enter the name of the repository",
    force_lock = "Force lock",
    force_lock_description = "Deposit lock force",
    impound_Deposit = "Seizure",
    impound_deposit_description = "Put the seal and seize",
    released = "Released",
    released_description = "Released from seizure",
    put_sale = "Relist for sale",
    put_sale_description = "Put up for sale",
    not_own_deposit ="You do not own this deposit",
    --Server
    no_money = "You don't have enough cash with you",
    sell_deposit = "You no longer have the deposit",
    deposit_rent = "You have rented a deposit",
    pay_rent = "You paid the deposit rent",    
    no_bank_money = "You don't have enough money in the bank to pay the deposit",
    no_money_impound = "Your deposit has been seized",
    deposit_seize = "You seized the deposit",
    lock_changed = "You changed the lock",
    key_duplicate = "You duplicated the key",
    unsealed_deposit = "You have unsealed the vault",
    deposit_relisted = "You have relisted the depot",
    --Keys and inventory name 
    keys = "Key of",
    inventory = "Inventory",
    impound = "Impound",

}   